name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 * * * *"
  watch:
    types: started
jobs:
  update-gist:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ab76976e617d06b58d48ebf333cae77d
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
